[package]
name = "svs_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
jpeg2k = "0.7.0"
rayon = "1.10.0"
iterators_extended = "0.1.0"
